server.default_listen_address=0.0.0.0
server.bolt.listen_address=:7687
server.bolt.tls_level=REQUIRED
server.http.enabled=false
server.https.enabled=false
dbms.ssl.policy.bolt.enabled=true
dbms.ssl.policy.bolt.base_directory=/runtime/tls
dbms.ssl.policy.bolt.private_key=localhost.key
dbms.ssl.policy.bolt.public_certificate=localhost.pem
dbms.ssl.policy.bolt.client_auth=NONE

