CREATE CONSTRAINT enterprise_object_identity IF NOT EXISTS FOR (resource:EnterpriseObject) REQUIRE (resource.tenantId, resource.resourceId) IS UNIQUE;
MERGE (contextPolicy:EnterpriseObject {tenantId:'demo-permit-authority',resourceId:'enterprise-object:permit-renewal-policy'}) SET contextPolicy.classification='Internal',contextPolicy.classificationRank=1,contextPolicy.contextContent='Synthetic demo policy: permit renewal requires an active permit, verified identity, and an eligibility decision recorded with evidence.',contextPolicy.contextRelevance=.99,contextPolicy.source='enterprise-model',contextPolicy.evidenceReferences=['evidence://demo/enterprise-context/permit-renewal-policy/001'];
MERGE (contextService:EnterpriseObject {tenantId:'demo-permit-authority',resourceId:'enterprise-object:permit-renewal-service'}) SET contextService.classification='Internal',contextService.classificationRank=1,contextService.contextContent='Synthetic demo service context: National Permit Renewal serves residents and permit officers through a governed renewal journey.',contextService.contextRelevance=.97,contextService.source='enterprise-model',contextService.evidenceReferences=['evidence://demo/enterprise-context/permit-renewal-service/001'];
MERGE (negative:EnterpriseObject {tenantId:'demo-permit-authority',resourceId:'enterprise-object:out-of-scope-control'}) SET negative.classification='Internal',negative.classificationRank=1,negative.contextContent='Synthetic negative fixture that must never be returned by the authorized scope.',negative.contextRelevance=1.0,negative.source='enterprise-model',negative.evidenceReferences=['evidence://demo/enterprise-context/out-of-scope/001'];
MERGE (a:EnterpriseObject {tenantId:'demo-permit-authority',resourceId:'11111111-1111-1111-1111-111111111111'}) SET a.type='PermitCaseService',a.state='Active',a.ownerId='demo-permit-authority',a.classification='Internal',a.classificationRank=1,a.policyReferences=['policy://demo/permit'],a.permittedActions=['renewal.read'],a.source='enterprise-model',a.sourceKind='enterprise-graph',a.confidence=.98,a.evidenceReferences=['evidence://demo/system/a'],a.lifecycle='Active',a.createdAt=datetime('2026-09-19T00:00:00Z'),a.updatedAt=datetime('2026-09-19T00:00:00Z'),a.credentialsIncluded=false,a.liveSessionIncluded=false,a.executableCommandIncluded=false,a.externalEffectOccurred=false;
MERGE (b:EnterpriseObject {tenantId:'demo-permit-authority',resourceId:'22222222-2222-2222-2222-222222222222'}) SET b.type='EligibilityRegistry',b.state='Active',b.ownerId='demo-permit-authority',b.classification='Internal',b.classificationRank=1,b.policyReferences=['policy://demo/eligibility'],b.permittedActions=['eligibility.read'],b.source='enterprise-model',b.sourceKind='enterprise-graph',b.confidence=.96,b.evidenceReferences=['evidence://demo/system/b'],b.lifecycle='Active',b.createdAt=datetime('2026-09-19T00:00:00Z'),b.updatedAt=datetime('2026-09-19T00:00:00Z'),b.credentialsIncluded=false,b.liveSessionIncluded=false,b.executableCommandIncluded=false,b.externalEffectOccurred=false;
MERGE (a)-[r:DependsOn]->(b) SET r.knowledgeState='Confirmed',r.confidence=.95,r.source='enterprise-model',r.evidenceReferences=['evidence://demo/relationship/a-b'],r.observedAt=datetime('2026-09-19T00:00:00Z');
MERGE (c:EnterpriseArchitecture {tenantId:'demo-permit-authority',architectureItemId:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'}) SET c.systemId='11111111-1111-1111-1111-111111111111',c.relatedSystemId='22222222-2222-2222-2222-222222222222',c.kind='Component',c.name='Permit case component',c.description='Synthetic approved component.',c.relationshipType='DependsOn',c.approvalState='Approved',c.version='1.0.0',c.classification='Internal',c.classificationRank=1,c.environment='IntegrationDemo',c.lifecycle='Active',c.sourceKind='enterprise-graph',c.evidenceReferences=['evidence://demo/architecture/component'],c.approvedAt=datetime('2026-09-19T00:00:00Z'),c.updatedAt=datetime('2026-09-19T00:00:00Z'),c.credentialsIncluded=false,c.liveSessionIncluded=false,c.executableCommandIncluded=false,c.generatedContentIncluded=false,c.externalEffectOccurred=false;
MERGE (i:EnterpriseArchitecture {tenantId:'demo-permit-authority',architectureItemId:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'}) SET i.systemId='22222222-2222-2222-2222-222222222222',i.kind='Interface',i.name='Eligibility interface',i.description='Synthetic approved interface.',i.approvalState='Approved',i.version='1.0.0',i.classification='Internal',i.classificationRank=1,i.environment='IntegrationDemo',i.lifecycle='Active',i.sourceKind='enterprise-graph',i.evidenceReferences=['evidence://demo/architecture/interface'],i.approvedAt=datetime('2026-09-19T00:00:00Z'),i.updatedAt=datetime('2026-09-19T00:00:00Z'),i.credentialsIncluded=false,i.liveSessionIncluded=false,i.executableCommandIncluded=false,i.generatedContentIncluded=false,i.externalEffectOccurred=false;

