package geaip
import rego.v1

decision := response("Permit",["demo_intent_registration_permitted"],null) if { common; input.action == "internal-service.intent.register"; input.classification in {"Public","Internal"} }
decision := response("Deny",["demo_intent_registration_denied"],null) if { input.action == "internal-service.intent.register"; not common }
decision := response("Permit",["demo_enterprise_context_permitted"],context_scope) if { common; input.action == "internal-service.enterprise-context.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_enterprise_context_denied"],null) if { input.action == "internal-service.enterprise-context.discover"; not common }
decision := response("Permit",["demo_existing_systems_permitted"],systems_scope) if { common; input.action == "internal-service.existing-systems.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_existing_systems_denied"],null) if { input.action == "internal-service.existing-systems.discover"; not common }
decision := response("Permit",["demo_existing_architecture_permitted"],architecture_scope) if { common; input.action == "internal-service.existing-architecture.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_existing_architecture_denied"],null) if { input.action == "internal-service.existing-architecture.discover"; not common }
decision := response("Permit",["demo_approved_packages_permitted"],packages_scope) if { common; input.action == "internal-service.approved-packages.select"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.coordinateCount == "2" }
decision := response("Deny",["demo_approved_packages_denied"],null) if { input.action == "internal-service.approved-packages.select"; not common }
decision := response("Permit",["demo_ai_planning_permitted"],planning_scope) if { common; input.action == "internal-service.ai-planning.create"; input.classification == "Internal"; input.attributes.promptTemplateId == "demo-internal-service-planning"; input.attributes.promptTemplateVersion == "1.0.0"; input.attributes.runtimeProfile == "demo-sovereign-planner"; input.attributes.contextReferenceCount == "4"; input.attributes.packageCount == "2"; input.attributes.constraintCount == "4"; count(planning_contexts) == 4 }
decision := response("Deny",["demo_ai_planning_denied"],null) if { input.action == "internal-service.ai-planning.create"; not common }
decision := response("Permit",["demo_code_generation_permitted"],code_generation_scope) if { common; input.action == "internal-service.code-generation.create"; input.classification == "Internal"; input.attributes.promptTemplateId == "demo-internal-service-code-generation"; input.attributes.promptTemplateVersion == "1.0.0"; input.attributes.runtimeProfile == "demo-sovereign-code-generator"; input.attributes.contextReferenceCount == "5"; input.attributes.packageCount == "2"; input.attributes.constraintCount == "4"; input.attributes.outputPathCount == "2"; count(code_generation_contexts) == 5 }
decision := response("Deny",["demo_code_generation_denied"],null) if { input.action == "internal-service.code-generation.create"; not common }
decision := response("Permit",["demo_static_validation_permitted"],static_validation_scope) if { common; input.action == "internal-service.static-validation.create"; input.classification == "Internal"; input.attributes.requiredControlCount == "2" }
decision := response("Deny",["demo_static_validation_denied"],null) if { input.action == "internal-service.static-validation.create"; not common }
decision := response("Permit",["demo_security_validation_permitted"],security_validation_scope) if { common; input.action == "internal-service.security-validation.create"; input.classification == "Internal"; input.attributes.requiredControlCount == "2" }
decision := response("Deny",["demo_security_validation_denied"],null) if { input.action == "internal-service.security-validation.create"; not common }
decision := response("Permit",["demo_sandbox_permitted"],sandbox_scope) if { common; input.action == "internal-service.sandbox.execute"; input.classification == "Internal"; input.attributes.sandboxImage == "SandboxImage|Platform.Synthetic.Permit.Sandbox|1.0.0|sha256:3333333333333333333333333333333333333333333333333333333333333333"; input.attributes.isolationClass == "Firecracker-class"; input.attributes.ephemeral == "True"; input.attributes.microVmIsolation == "True"; input.attributes.productionCredentialsAllowed == "False"; input.attributes.hostFilesystemAccessAllowed == "False"; input.attributes.networkDefaultDeny == "True"; input.attributes.cpuLimit == "1"; input.attributes.memoryLimitBytes == "536870912"; input.attributes.executionTimeoutTicks == "300000000"; input.attributes.environmentReferences == "CONFIG_PROFILE=reference://demo/config/permit-sandbox-v1"; input.attributes.networkDestinations == "" }
decision := response("Deny",["demo_sandbox_denied"],null) if { input.action == "internal-service.sandbox.execute"; not common }
decision := response("Permit",["demo_tests_permitted"],tests_scope) if { tests_permitted }
decision := response("Deny",["demo_tests_denied"],null) if { input.action == "internal-service.tests.execute"; not tests_permitted }
tests_permitted if { common; input.action == "internal-service.tests.execute"; input.classification == "Internal"; input.attributes.testManifestReference == "manifest://demo/governed-tests/permit-renewal/v1"; input.attributes.testManifestSha256Digest == "5555555555555555555555555555555555555555555555555555555555555555"; input.attributes.requiredTestIds == "demo-tests-contract,demo-tests-policy-boundary"; input.attributes.allowedTestCategories == "Contract,Governance"; input.attributes.testImage == "SandboxImage|Platform.Synthetic.Permit.Tests|1.0.0|sha256:4444444444444444444444444444444444444444444444444444444444444444"; input.attributes.isolation == "Firecracker-class|True|True|False|False|True|1|536870912|300000000|"; input.attributes.environmentReferences == "TEST_PROFILE=reference://demo/config/permit-tests-v1" }
decision := response("Permit",["demo_human_review_permitted"],human_review_scope) if { human_review_permitted }
decision := response("Deny",["demo_human_review_denied"],null) if { input.action == "internal-service.human-review.decide"; not human_review_permitted }
human_review_permitted if { common; input.action == "internal-service.human-review.decide"; input.classification == "Internal"; input.subjectId == "10000000-0000-0000-0000-000000000013"; input.attributes.reviewerSubjectId == input.subjectId; input.attributes.initiatorSubjectId == "10000000-0000-0000-0000-000000000012"; input.attributes.humanDecision in {"Approve","Reject"}; input.attributes.rationaleSha256Digest != ""; input.attributes.humanAttestationReference != ""; input.attributes.conflictingSubjectIds == input.attributes.initiatorSubjectId; input.attributes.expectedVersion == "-1" }
decision := response("Permit",["demo_git_permitted"],git_scope) if { git_permitted }
decision := response("Deny",["demo_git_denied"],null) if { input.action == "internal-service.git.commit"; not git_permitted }
git_permitted if { common; input.action == "internal-service.git.commit"; input.classification == "Internal"; input.attributes.candidateSha256Digest != ""; input.attributes.reviewPackageSha256Digest != ""; input.attributes.reviewEvidenceReference != ""; input.attributes.testsResultSha256Digest != ""; input.attributes.changeSetSha256Digest != ""; input.attributes.authorizedRelativePaths == "backend/Generated/PermitRenewalService.cs,frontend/Generated/PermitRenewalView.razor"; input.attributes.repositoryId == "repository://demo/permit-renewal-service"; input.attributes.expectedBaseCommitId == "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"; input.attributes.changeBranch == "changes/demo-permit-renewal-stage-14"; input.attributes.commitMessage == "feat(permit): add reviewed renewal service"; input.attributes.signingPolicyReference == "policy://demo/git-signing/v1" }

common if { input.environment == "IntegrationDemo"; input.tenantId == "demo-permit-authority"; input.purpose == "internal-service-delivery-demonstration"; input.verifiedPolicyBundle.signatureValid == true; input.verifiedPolicyBundle.bundleId == "geaip-demo-stage-14"; input.verifiedPolicyBundle.version == "2026.09.23"; input.verifiedPolicyBundle.sha256Digest == "d03618d00a43e9a679db69af965a840fdb3198e69b98d31e497bdd418c3e1117" }

empty := {"maximumClassification":"","allowedResourceIds":[],"allowedModalities":[],"requiredRoles":[],"maximumResults":0,"existingSystems":null,"existingArchitecture":null,"approvedPackages":null,"aiPlanning":null,"codeGeneration":null,"staticValidation":null,"securityValidation":null,"sandbox":null,"tests":null,"humanReview":null,"git":null,"ciCd":null,"artifact":null,"deployment":null,"openTelemetry":null,"automaticRegistration":null,"enterpriseModel":null,"evidenceCompletion":null}
context_scope := object.union(empty,{"maximumClassification":"Internal","allowedResourceIds":["enterprise-object:permit-renewal-policy","enterprise-object:permit-renewal-service"],"allowedModalities":["Graph"],"maximumResults":2})
systems_scope := object.union(empty,{"existingSystems":{"maximumClassification":"Internal","allowedSystemIds":["11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"],"allowedRelationshipTypes":["DependsOn"],"allowedSourceKind":"enterprise-graph","requiredRoles":["Developer"],"maximumResults":2}})
architecture_scope := object.union(empty,{"existingArchitecture":{"maximumClassification":"Internal","allowedSystemIds":["11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"],"allowedItemKinds":["Component","Interface"],"allowedRelationshipTypes":["DependsOn"],"allowedSourceKind":"enterprise-graph","requiredRoles":["Developer"],"maximumResults":2}})
packages_scope := object.union(empty,{"approvedPackages":{"maximumClassification":"Internal","allowedCoordinates":[{"kind":"NuGet","name":"Platform.Synthetic.Permit.Contracts","version":"1.0.0","contentDigest":"sha256:1111111111111111111111111111111111111111111111111111111111111111"},{"kind":"FrontendDependency","name":"@geaip/permit-ui-contracts","version":"1.0.0","contentDigest":"sha256:2222222222222222222222222222222222222222222222222222222222222222"}],"requiredRoles":["Developer"],"maximumResults":2}})
planning_contexts := {reference | some reference in input.evidenceReferences; regex.match("^evidence://(enterprise-context|existing-systems|existing-architecture|approved-packages)/[0-9a-f-]{36}/sha256/[0-9a-f]{64}$",reference)}
planning_scope := object.union(empty,{"aiPlanning":{"maximumClassification":"Internal","allowedPromptTemplateId":"demo-internal-service-planning","allowedPromptTemplateVersion":"1.0.0","allowedPromptSha256Digest":"996dc1d8964bab91d4db217c9e0d3d439898c34d76f95de1ad546d4061298fef","allowedRuntimeProfile":"demo-sovereign-planner","allowedContextReferences":sort(planning_contexts),"allowedPackages":[{"kind":"NuGet","name":"Platform.Synthetic.Permit.Contracts","version":"1.0.0","contentDigest":"sha256:1111111111111111111111111111111111111111111111111111111111111111"},{"kind":"FrontendDependency","name":"@geaip/permit-ui-contracts","version":"1.0.0","contentDigest":"sha256:2222222222222222222222222222222222222222222222222222222222222222"}],"allowedConstraints":["planning-only","no-tools","no-generated-files","no-workflow-advancement"],"requiredRoles":["Developer"],"outputKind":"planning","requestTimeoutSeconds":10,"maximumRequestBytes":65536,"maximumResponseBytes":65536}})
code_generation_contexts := {reference | some reference in input.evidenceReferences; regex.match("^evidence://(enterprise-context|existing-systems|existing-architecture|approved-packages|ai-planning)/[0-9a-f-]{36}/sha256/[0-9a-f]{64}$",reference)}
code_generation_scope := object.union(empty,{"codeGeneration":{"maximumClassification":"Internal","allowedPromptTemplateId":"demo-internal-service-code-generation","allowedPromptTemplateVersion":"1.0.0","allowedPromptSha256Digest":"d01ae4012a2b374a3e9b1ec305472dbfb9bee8b131f2719c3505c365963246a8","allowedRuntimeProfile":"demo-sovereign-code-generator","allowedContextReferences":sort(code_generation_contexts),"allowedPackages":[{"kind":"NuGet","name":"Platform.Synthetic.Permit.Contracts","version":"1.0.0","contentDigest":"sha256:1111111111111111111111111111111111111111111111111111111111111111"},{"kind":"FrontendDependency","name":"@geaip/permit-ui-contracts","version":"1.0.0","contentDigest":"sha256:2222222222222222222222222222222222222222222222222222222222222222"}],"allowedConstraints":["inert-content-only","no-tools","no-commands","no-file-application"],"allowedOutputPaths":["backend/Generated/PermitRenewalService.cs","frontend/Generated/PermitRenewalView.razor"],"requiredRoles":["Developer"],"outputKind":"inert-code-candidate","requestTimeoutSeconds":10,"maximumRequestBytes":65536,"maximumResponseBytes":65536}})
static_validation_scope := object.union(empty,{"staticValidation":{"maximumClassification":"Internal","allowedControlIds":["demo-static-contract-shape","demo-static-source-boundary"],"requiredRoles":["Developer"],"outputKind":"static-report"}})
security_validation_scope := object.union(empty,{"securityValidation":{"maximumClassification":"Internal","allowedControlIds":["demo-security-data-flow","demo-security-input-boundary"],"requiredRoles":["Developer"],"outputKind":"security-report"}})
sandbox_scope := object.union(empty,{"sandbox":{"maximumClassification":"Internal","allowedSandboxImage":{"kind":"SandboxImage","name":"Platform.Synthetic.Permit.Sandbox","version":"1.0.0","contentDigest":"sha256:3333333333333333333333333333333333333333333333333333333333333333"},"isolationClass":"Firecracker-class","ephemeral":true,"microVmIsolation":true,"productionCredentialsAllowed":false,"hostFilesystemAccessAllowed":false,"networkDefaultDeny":true,"cpuLimit":1,"memoryLimitBytes":536870912,"executionTimeoutTicks":300000000,"allowedEnvironmentReferences":{"CONFIG_PROFILE":"reference://demo/config/permit-sandbox-v1"},"allowedNetworkDestinations":[],"requiredRoles":["Developer"],"outputKind":"sandbox-result"}})
tests_scope := object.union(empty,{"tests":{"maximumClassification":"Internal","testManifestReference":"manifest://demo/governed-tests/permit-renewal/v1","testManifestSha256Digest":"5555555555555555555555555555555555555555555555555555555555555555","requiredTestIds":["demo-tests-contract","demo-tests-policy-boundary"],"allowedTestCategories":["Contract","Governance"],"allowedTestImage":{"kind":"SandboxImage","name":"Platform.Synthetic.Permit.Tests","version":"1.0.0","contentDigest":"sha256:4444444444444444444444444444444444444444444444444444444444444444"},"isolationClass":"Firecracker-class","ephemeral":true,"microVmIsolation":true,"productionCredentialsAllowed":false,"hostFilesystemAccessAllowed":false,"networkDefaultDeny":true,"cpuLimit":1,"memoryLimitBytes":536870912,"executionTimeoutTicks":300000000,"allowedEnvironmentReferences":{"TEST_PROFILE":"reference://demo/config/permit-tests-v1"},"allowedNetworkDestinations":[],"requiredRoles":["Developer"],"outputKind":"tests-result"}})
human_review_scope := object.union(empty,{"humanReview":{"maximumClassification":"Internal","reviewerSubjectId":input.attributes.reviewerSubjectId,"initiatorSubjectId":input.attributes.initiatorSubjectId,"humanDecision":input.attributes.humanDecision,"rationaleSha256Digest":input.attributes.rationaleSha256Digest,"humanAttestationReference":input.attributes.humanAttestationReference,"conflictingSubjectIds":[input.attributes.initiatorSubjectId],"reviewerIsHuman":true,"expectedVersion":-1,"requiredRoles":["HumanReviewer"],"outputKind":"human-review-decision"}})
git_scope := object.union(empty,{"git":{"maximumClassification":"Internal","allowedRelativePaths":["backend/Generated/PermitRenewalService.cs","frontend/Generated/PermitRenewalView.razor"],"repositoryId":"repository://demo/permit-renewal-service","expectedBaseCommitId":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","changeBranch":"changes/demo-permit-renewal-stage-14","commitMessage":"feat(permit): add reviewed renewal service","signingPolicyReference":"policy://demo/git-signing/v1","protectedBranch":false,"forceUpdateAllowed":false,"ciCdTriggerAllowed":false,"requiredRoles":["Developer"],"outputKind":"git-commit-result"}})
response(outcome,reasons,resultscope) := {"decisionRequestId":input.decisionRequestId,"action":input.action,"resourceId":input.resourceId,"bundleId":input.verifiedPolicyBundle.bundleId,"bundleVersion":input.verifiedPolicyBundle.version,"bundleSha256Digest":input.verifiedPolicyBundle.sha256Digest,"environment":input.environment,"outcome":outcome,"reasons":reasons,"evidenceReferences":[sprintf("evidence://demo/opa/decisions/%s",[input.decisionRequestId])],"scope":resultscope,"decidedAt":input.evaluatedAt}
