package geaip
import rego.v1

decision := response("Permit",["demo_intent_registration_permitted"],null) if { common; input.action == "internal-service.intent.register"; input.classification in {"Public","Internal"} }
decision := response("Deny",["demo_intent_registration_denied"],null) if { input.action == "internal-service.intent.register"; not common }
decision := response("Permit",["demo_enterprise_context_permitted"],context_scope) if { common; input.action == "internal-service.enterprise-context.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_enterprise_context_denied"],null) if { input.action == "internal-service.enterprise-context.discover"; not common }
decision := response("Permit",["demo_existing_systems_permitted"],systems_scope) if { common; input.action == "internal-service.existing-systems.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_existing_systems_denied"],null) if { input.action == "internal-service.existing-systems.discover"; not common }
decision := response("Permit",["demo_existing_architecture_permitted"],architecture_scope) if { common; input.action == "internal-service.existing-architecture.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_existing_architecture_denied"],null) if { input.action == "internal-service.existing-architecture.discover"; not common }
decision := response("Permit",["demo_approved_packages_permitted"],packages_scope) if { common; input.action == "internal-service.approved-packages.select"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.coordinateCount == "2" }
decision := response("Deny",["demo_approved_packages_denied"],null) if { input.action == "internal-service.approved-packages.select"; not common }
decision := response("Permit",["demo_ai_planning_permitted"],planning_scope) if { common; input.action == "internal-service.ai-planning.create"; input.classification == "Internal"; input.attributes.promptTemplateId == "demo-internal-service-planning"; input.attributes.promptTemplateVersion == "1.0.0"; input.attributes.runtimeProfile == "demo-sovereign-planner"; input.attributes.contextReferenceCount == "4"; input.attributes.packageCount == "2"; input.attributes.constraintCount == "4"; count(planning_contexts) == 4 }
decision := response("Deny",["demo_ai_planning_denied"],null) if { input.action == "internal-service.ai-planning.create"; not common }
decision := response("Permit",["demo_code_generation_permitted"],code_generation_scope) if { common; input.action == "internal-service.code-generation.create"; input.classification == "Internal"; input.attributes.promptTemplateId == "demo-internal-service-code-generation"; input.attributes.promptTemplateVersion == "1.0.0"; input.attributes.runtimeProfile == "demo-sovereign-code-generator"; input.attributes.contextReferenceCount == "5"; input.attributes.packageCount == "2"; input.attributes.constraintCount == "4"; input.attributes.outputPathCount == "2"; count(code_generation_contexts) == 5 }
decision := response("Deny",["demo_code_generation_denied"],null) if { input.action == "internal-service.code-generation.create"; not common }
decision := response("Permit",["demo_static_validation_permitted"],static_validation_scope) if { common; input.action == "internal-service.static-validation.create"; input.classification == "Internal"; input.attributes.requiredControlCount == "2" }
decision := response("Deny",["demo_static_validation_denied"],null) if { input.action == "internal-service.static-validation.create"; not common }
decision := response("Permit",["demo_security_validation_permitted"],security_validation_scope) if { common; input.action == "internal-service.security-validation.create"; input.classification == "Internal"; input.attributes.requiredControlCount == "2" }
decision := response("Deny",["demo_security_validation_denied"],null) if { input.action == "internal-service.security-validation.create"; not common }
decision := response("Permit",["demo_sandbox_permitted"],sandbox_scope) if { common; input.action == "internal-service.sandbox.execute"; input.classification == "Internal"; input.attributes.sandboxImage == "SandboxImage|Platform.Synthetic.Permit.Sandbox|1.0.0|sha256:3333333333333333333333333333333333333333333333333333333333333333"; input.attributes.isolationClass == "Firecracker-class"; input.attributes.ephemeral == "True"; input.attributes.microVmIsolation == "True"; input.attributes.productionCredentialsAllowed == "False"; input.attributes.hostFilesystemAccessAllowed == "False"; input.attributes.networkDefaultDeny == "True"; input.attributes.cpuLimit == "1"; input.attributes.memoryLimitBytes == "536870912"; input.attributes.executionTimeoutTicks == "300000000"; input.attributes.environmentReferences == "CONFIG_PROFILE=reference://demo/config/permit-sandbox-v1"; input.attributes.networkDestinations == "" }
decision := response("Deny",["demo_sandbox_denied"],null) if { input.action == "internal-service.sandbox.execute"; not common }

common if { input.environment == "IntegrationDemo"; input.tenantId == "demo-permit-authority"; input.purpose == "internal-service-delivery-demonstration"; input.verifiedPolicyBundle.signatureValid == true; input.verifiedPolicyBundle.bundleId == "geaip-demo-stage-11"; input.verifiedPolicyBundle.version == "2026.09.19"; input.verifiedPolicyBundle.sha256Digest == "bfa13a11c0864ed01b8ea3756e612cdc313fb1fac8600e4b117d27b3f6329467" }

empty := {"maximumClassification":"","allowedResourceIds":[],"allowedModalities":[],"requiredRoles":[],"maximumResults":0,"existingSystems":null,"existingArchitecture":null,"approvedPackages":null,"aiPlanning":null,"codeGeneration":null,"staticValidation":null,"securityValidation":null,"sandbox":null,"tests":null,"humanReview":null,"git":null,"ciCd":null,"artifact":null,"deployment":null,"openTelemetry":null,"automaticRegistration":null,"enterpriseModel":null,"evidenceCompletion":null}
context_scope := object.union(empty,{"maximumClassification":"Internal","allowedResourceIds":["enterprise-object:permit-renewal-policy","enterprise-object:permit-renewal-service"],"allowedModalities":["Graph"],"maximumResults":2})
systems_scope := object.union(empty,{"existingSystems":{"maximumClassification":"Internal","allowedSystemIds":["11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"],"allowedRelationshipTypes":["DependsOn"],"allowedSourceKind":"enterprise-graph","requiredRoles":["Developer"],"maximumResults":2}})
architecture_scope := object.union(empty,{"existingArchitecture":{"maximumClassification":"Internal","allowedSystemIds":["11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"],"allowedItemKinds":["Component","Interface"],"allowedRelationshipTypes":["DependsOn"],"allowedSourceKind":"enterprise-graph","requiredRoles":["Developer"],"maximumResults":2}})
packages_scope := object.union(empty,{"approvedPackages":{"maximumClassification":"Internal","allowedCoordinates":[{"kind":"NuGet","name":"Platform.Synthetic.Permit.Contracts","version":"1.0.0","contentDigest":"sha256:1111111111111111111111111111111111111111111111111111111111111111"},{"kind":"FrontendDependency","name":"@geaip/permit-ui-contracts","version":"1.0.0","contentDigest":"sha256:2222222222222222222222222222222222222222222222222222222222222222"}],"requiredRoles":["Developer"],"maximumResults":2}})
planning_contexts := {reference | some reference in input.evidenceReferences; regex.match("^evidence://(enterprise-context|existing-systems|existing-architecture|approved-packages)/[0-9a-f-]{36}/sha256/[0-9a-f]{64}$",reference)}
planning_scope := object.union(empty,{"aiPlanning":{"maximumClassification":"Internal","allowedPromptTemplateId":"demo-internal-service-planning","allowedPromptTemplateVersion":"1.0.0","allowedPromptSha256Digest":"996dc1d8964bab91d4db217c9e0d3d439898c34d76f95de1ad546d4061298fef","allowedRuntimeProfile":"demo-sovereign-planner","allowedContextReferences":sort(planning_contexts),"allowedPackages":[{"kind":"NuGet","name":"Platform.Synthetic.Permit.Contracts","version":"1.0.0","contentDigest":"sha256:1111111111111111111111111111111111111111111111111111111111111111"},{"kind":"FrontendDependency","name":"@geaip/permit-ui-contracts","version":"1.0.0","contentDigest":"sha256:2222222222222222222222222222222222222222222222222222222222222222"}],"allowedConstraints":["planning-only","no-tools","no-generated-files","no-workflow-advancement"],"requiredRoles":["Developer"],"outputKind":"planning","requestTimeoutSeconds":10,"maximumRequestBytes":65536,"maximumResponseBytes":65536}})
code_generation_contexts := {reference | some reference in input.evidenceReferences; regex.match("^evidence://(enterprise-context|existing-systems|existing-architecture|approved-packages|ai-planning)/[0-9a-f-]{36}/sha256/[0-9a-f]{64}$",reference)}
code_generation_scope := object.union(empty,{"codeGeneration":{"maximumClassification":"Internal","allowedPromptTemplateId":"demo-internal-service-code-generation","allowedPromptTemplateVersion":"1.0.0","allowedPromptSha256Digest":"d01ae4012a2b374a3e9b1ec305472dbfb9bee8b131f2719c3505c365963246a8","allowedRuntimeProfile":"demo-sovereign-code-generator","allowedContextReferences":sort(code_generation_contexts),"allowedPackages":[{"kind":"NuGet","name":"Platform.Synthetic.Permit.Contracts","version":"1.0.0","contentDigest":"sha256:1111111111111111111111111111111111111111111111111111111111111111"},{"kind":"FrontendDependency","name":"@geaip/permit-ui-contracts","version":"1.0.0","contentDigest":"sha256:2222222222222222222222222222222222222222222222222222222222222222"}],"allowedConstraints":["inert-content-only","no-tools","no-commands","no-file-application"],"allowedOutputPaths":["backend/Generated/PermitRenewalService.cs","frontend/Generated/PermitRenewalView.razor"],"requiredRoles":["Developer"],"outputKind":"inert-code-candidate","requestTimeoutSeconds":10,"maximumRequestBytes":65536,"maximumResponseBytes":65536}})
static_validation_scope := object.union(empty,{"staticValidation":{"maximumClassification":"Internal","allowedControlIds":["demo-static-contract-shape","demo-static-source-boundary"],"requiredRoles":["Developer"],"outputKind":"static-report"}})
security_validation_scope := object.union(empty,{"securityValidation":{"maximumClassification":"Internal","allowedControlIds":["demo-security-data-flow","demo-security-input-boundary"],"requiredRoles":["Developer"],"outputKind":"security-report"}})
sandbox_scope := object.union(empty,{"sandbox":{"maximumClassification":"Internal","allowedSandboxImage":{"kind":"SandboxImage","name":"Platform.Synthetic.Permit.Sandbox","version":"1.0.0","contentDigest":"sha256:3333333333333333333333333333333333333333333333333333333333333333"},"isolationClass":"Firecracker-class","ephemeral":true,"microVmIsolation":true,"productionCredentialsAllowed":false,"hostFilesystemAccessAllowed":false,"networkDefaultDeny":true,"cpuLimit":1,"memoryLimitBytes":536870912,"executionTimeoutTicks":300000000,"allowedEnvironmentReferences":{"CONFIG_PROFILE":"reference://demo/config/permit-sandbox-v1"},"allowedNetworkDestinations":[],"requiredRoles":["Developer"],"outputKind":"sandbox-result"}})
response(outcome,reasons,resultscope) := {"decisionRequestId":input.decisionRequestId,"action":input.action,"resourceId":input.resourceId,"bundleId":input.verifiedPolicyBundle.bundleId,"bundleVersion":input.verifiedPolicyBundle.version,"bundleSha256Digest":input.verifiedPolicyBundle.sha256Digest,"environment":input.environment,"outcome":outcome,"reasons":reasons,"evidenceReferences":[sprintf("evidence://demo/opa/decisions/%s",[input.decisionRequestId])],"scope":resultscope,"decidedAt":input.evaluatedAt}
