package geaip
import rego.v1

decision := response("Permit",["demo_intent_registration_permitted"],null) if { common; input.action == "internal-service.intent.register"; input.classification in {"Public","Internal"} }
decision := response("Deny",["demo_intent_registration_denied"],null) if { input.action == "internal-service.intent.register"; not common }
decision := response("Permit",["demo_enterprise_context_permitted"],context_scope) if { common; input.action == "internal-service.enterprise-context.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_enterprise_context_denied"],null) if { input.action == "internal-service.enterprise-context.discover"; not common }
decision := response("Permit",["demo_existing_systems_permitted"],systems_scope) if { common; input.action == "internal-service.existing-systems.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_existing_systems_denied"],null) if { input.action == "internal-service.existing-systems.discover"; not common }

common if { input.environment == "IntegrationDemo"; input.tenantId == "demo-permit-authority"; input.purpose == "internal-service-delivery-demonstration"; input.verifiedPolicyBundle.signatureValid == true; input.verifiedPolicyBundle.bundleId == "geaip-demo-stage-04"; input.verifiedPolicyBundle.version == "2026.09.18"; input.verifiedPolicyBundle.sha256Digest == "39bc32b9113da01093a764ff50969c8c70682c2f543b07de9609b4362ea76484" }

context_scope := {"maximumClassification":"Internal","allowedResourceIds":["enterprise-object:permit-renewal-policy","enterprise-object:permit-renewal-service"],"allowedModalities":["Graph"],"requiredRoles":[],"maximumResults":2,"existingSystems":null,"existingArchitecture":null,"approvedPackages":null,"aiPlanning":null,"codeGeneration":null,"staticValidation":null,"securityValidation":null,"sandbox":null,"tests":null,"humanReview":null,"git":null,"ciCd":null,"artifact":null,"deployment":null,"openTelemetry":null,"automaticRegistration":null,"enterpriseModel":null,"evidenceCompletion":null}
systems_scope := {"maximumClassification":"","allowedResourceIds":[],"allowedModalities":[],"requiredRoles":[],"maximumResults":0,"existingSystems":{"maximumClassification":"Internal","allowedSystemIds":["11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"],"allowedRelationshipTypes":["DependsOn"],"allowedSourceKind":"enterprise-graph","requiredRoles":["Developer"],"maximumResults":2},"existingArchitecture":null,"approvedPackages":null,"aiPlanning":null,"codeGeneration":null,"staticValidation":null,"securityValidation":null,"sandbox":null,"tests":null,"humanReview":null,"git":null,"ciCd":null,"artifact":null,"deployment":null,"openTelemetry":null,"automaticRegistration":null,"enterpriseModel":null,"evidenceCompletion":null}
response(outcome,reasons,scope) := {"decisionRequestId":input.decisionRequestId,"action":input.action,"resourceId":input.resourceId,"bundleId":input.verifiedPolicyBundle.bundleId,"bundleVersion":input.verifiedPolicyBundle.version,"bundleSha256Digest":input.verifiedPolicyBundle.sha256Digest,"environment":input.environment,"outcome":outcome,"reasons":reasons,"evidenceReferences":[sprintf("evidence://demo/opa/decisions/%s",[input.decisionRequestId])],"scope":scope,"decidedAt":input.evaluatedAt}
