package geaip
import rego.v1

decision := response("Permit",["demo_intent_registration_permitted"],null) if { common; input.action == "internal-service.intent.register"; input.classification in {"Public","Internal"} }
decision := response("Deny",["demo_intent_registration_denied"],null) if { input.action == "internal-service.intent.register"; not common }
decision := response("Permit",["demo_enterprise_context_permitted"],context_scope) if { common; input.action == "internal-service.enterprise-context.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_enterprise_context_denied"],null) if { input.action == "internal-service.enterprise-context.discover"; not common }
decision := response("Permit",["demo_existing_systems_permitted"],systems_scope) if { common; input.action == "internal-service.existing-systems.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_existing_systems_denied"],null) if { input.action == "internal-service.existing-systems.discover"; not common }
decision := response("Permit",["demo_existing_architecture_permitted"],architecture_scope) if { common; input.action == "internal-service.existing-architecture.discover"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.intentSha256Digest == "6d4b8c396f0d0b1f692b9aa7f4c0a9bc5ee26d5775f6e74bdab76a01ec3d7d1e" }
decision := response("Deny",["demo_existing_architecture_denied"],null) if { input.action == "internal-service.existing-architecture.discover"; not common }
decision := response("Permit",["demo_approved_packages_permitted"],packages_scope) if { common; input.action == "internal-service.approved-packages.select"; input.classification == "Internal"; input.attributes.registrationVersion == "0"; input.attributes.coordinateCount == "2" }
decision := response("Deny",["demo_approved_packages_denied"],null) if { input.action == "internal-service.approved-packages.select"; not common }

common if { input.environment == "IntegrationDemo"; input.tenantId == "demo-permit-authority"; input.purpose == "internal-service-delivery-demonstration"; input.verifiedPolicyBundle.signatureValid == true; input.verifiedPolicyBundle.bundleId == "geaip-demo-stage-06"; input.verifiedPolicyBundle.version == "2026.09.19"; input.verifiedPolicyBundle.sha256Digest == "d478e05577434db063f0424b2c8642b9073c2f0fa61e188b28bcd1fae87cb15a" }

empty := {"maximumClassification":"","allowedResourceIds":[],"allowedModalities":[],"requiredRoles":[],"maximumResults":0,"existingSystems":null,"existingArchitecture":null,"approvedPackages":null,"aiPlanning":null,"codeGeneration":null,"staticValidation":null,"securityValidation":null,"sandbox":null,"tests":null,"humanReview":null,"git":null,"ciCd":null,"artifact":null,"deployment":null,"openTelemetry":null,"automaticRegistration":null,"enterpriseModel":null,"evidenceCompletion":null}
context_scope := object.union(empty,{"maximumClassification":"Internal","allowedResourceIds":["enterprise-object:permit-renewal-policy","enterprise-object:permit-renewal-service"],"allowedModalities":["Graph"],"maximumResults":2})
systems_scope := object.union(empty,{"existingSystems":{"maximumClassification":"Internal","allowedSystemIds":["11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"],"allowedRelationshipTypes":["DependsOn"],"allowedSourceKind":"enterprise-graph","requiredRoles":["Developer"],"maximumResults":2}})
architecture_scope := object.union(empty,{"existingArchitecture":{"maximumClassification":"Internal","allowedSystemIds":["11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"],"allowedItemKinds":["Component","Interface"],"allowedRelationshipTypes":["DependsOn"],"allowedSourceKind":"enterprise-graph","requiredRoles":["Developer"],"maximumResults":2}})
packages_scope := object.union(empty,{"approvedPackages":{"maximumClassification":"Internal","allowedCoordinates":[{"kind":"NuGet","name":"Platform.Synthetic.Permit.Contracts","version":"1.0.0","contentDigest":"sha256:1111111111111111111111111111111111111111111111111111111111111111"},{"kind":"FrontendDependency","name":"@geaip/permit-ui-contracts","version":"1.0.0","contentDigest":"sha256:2222222222222222222222222222222222222222222222222222222222222222"}],"requiredRoles":["Developer"],"maximumResults":2}})
response(outcome,reasons,resultscope) := {"decisionRequestId":input.decisionRequestId,"action":input.action,"resourceId":input.resourceId,"bundleId":input.verifiedPolicyBundle.bundleId,"bundleVersion":input.verifiedPolicyBundle.version,"bundleSha256Digest":input.verifiedPolicyBundle.sha256Digest,"environment":input.environment,"outcome":outcome,"reasons":reasons,"evidenceReferences":[sprintf("evidence://demo/opa/decisions/%s",[input.decisionRequestId])],"scope":resultscope,"decidedAt":input.evaluatedAt}
