param([switch]$StartInfrastructure)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$runtime=Join-Path $root '.runtime\integration-demo-stage-08';$tls=Join-Path $runtime 'tls';$keys=Join-Path $runtime 'opa';$source=Join-Path $root 'deploy\demo\stage-08\opa';$compose=Join-Path $root 'deploy\demo\stage-08\compose.yml';$seed=Join-Path $root 'deploy\demo\stage-08\neo4j\seed.cypher';$helper='postgres:18.6-bookworm@sha256:1c59e2c3c818eaa0f0628f695b36e7c9e362d6b219b36a54a32df645cbd7e1af';$opa='openpolicyagent/opa:1.20.2-static@sha256:bb245e9e36be0d0ed486c240b606c56be7aba96014a4a87895fed4ba7a6dfa8d'
if([string]::IsNullOrWhiteSpace($env:GEAIP_DEMO_POSTGRES_PASSWORD)-or $env:GEAIP_DEMO_POSTGRES_PASSWORD.Length -lt 16){throw 'GEAIP_DEMO_POSTGRES_PASSWORD must be supplied outside Git and contain at least 16 characters.'};if([string]::IsNullOrWhiteSpace($env:GEAIP_DEMO_NEO4J_PASSWORD)-or $env:GEAIP_DEMO_NEO4J_PASSWORD.Length -lt 16){throw 'GEAIP_DEMO_NEO4J_PASSWORD must be supplied outside Git and contain at least 16 characters.'}
New-Item -ItemType Directory -Force $tls,$keys,(Join-Path $runtime 'packages'),(Join-Path $runtime 'ai-planning'),(Join-Path $runtime 'code-generation')|Out-Null
& dotnet dev-certs https --trust --export-path (Join-Path $tls 'localhost.pem') --format Pem --no-password;if($LASTEXITCODE-ne 0){throw 'Trusted localhost PEM certificate export failed.'}
if(-not(Test-Path (Join-Path $keys 'private.pem'))){& docker run --rm --mount "type=bind,source=$keys,target=/keys" $helper bash -ec 'openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:3072 -out /keys/private.pem && openssl pkey -in /keys/private.pem -pubout -out /keys/public.pem';if($LASTEXITCODE-ne 0){throw 'OPA signing-key generation failed.'}};& docker run --rm --mount "type=bind,source=$keys,target=/keys" $helper bash -ec 'chown -R 1000:1000 /keys && chmod 600 /keys/private.pem && chmod 644 /keys/public.pem';if($LASTEXITCODE-ne 0){throw 'OPA signing-key permission preparation failed.'}
& docker run --rm --mount "type=bind,source=$source,target=/bundle-source,readonly" --mount "type=bind,source=$keys,target=/runtime" $opa build --bundle /bundle-source --output /runtime/bundle.tar.gz --revision geaip-demo-stage-08-2026.09.19 --signing-key /runtime/private.pem --signing-alg RS256;if($LASTEXITCODE-ne 0){throw 'Signed OPA bundle creation failed.'}
if($StartInfrastructure){$packageSeed=Join-Path $runtime 'packages\seed.sql';$planningSeed=Join-Path $runtime 'ai-planning\seed.sql';$codeSeed=Join-Path $runtime 'code-generation\seed.sql';if(-not(Test-Path $packageSeed)){throw 'The signed synthetic package-catalog seed must be provisioned outside Git before Stage 08 infrastructure starts.'};if(-not(Test-Path $planningSeed)){throw 'The signed governed planning-prompt seed must be provisioned outside Git before Stage 08 infrastructure starts.'};if(-not(Test-Path $codeSeed)){throw 'The signed governed Code Generation prompt seed must be provisioned outside Git before Stage 08 infrastructure starts.'};& docker compose -f $compose up -d;if($LASTEXITCODE-ne 0){throw 'Stage 08 infrastructure startup failed.'};$ok=$false;foreach($attempt in 1..30){Start-Sleep -Seconds 2;Get-Content -Raw $seed|docker compose -f $compose exec -T neo4j cypher-shell -a neo4j+ssc://localhost:7687 -u neo4j -p $env:GEAIP_DEMO_NEO4J_PASSWORD --format plain;if($LASTEXITCODE-eq 0){$ok=$true;break}};if(-not $ok){throw 'Synthetic graph seeding failed.'}}
Write-Output 'Stage 08 runtime material is prepared outside Git.'
