using System.Collections.Immutable;
using System.Data;
using System.Text.Json;
using Microsoft.Extensions.Options;
using Npgsql;
using NpgsqlTypes;
using Platform.SoftwareFactory.Delivery;
using Platform.SoftwareFactory.InternalService;

namespace Platform.SoftwareFactory.Persistence;

public sealed class PostgreSqlGitHumanReviewReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IGitHumanReviewReceiptReader
{
 public async Task<GovernedHumanReviewReceipt?> LoadAsync(Guid id,string tenant,string purpose,Guid tests,Guid generation,Guid run,string candidate,string package,string evidence,string testsResult,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new GitDependencyUnavailableException("Human Review evidence not configured.");const string sql="SELECT h.record_json,h.record_sha256_digest,h.evidence_reference,h.evidence_references,h.recorded_at,h.version,t.record_json FROM software_factory.human_review_evidence h JOIN software_factory.tests_evidence t ON t.tenant_id=h.tenant_id AND t.execution_id=h.tests_execution_id WHERE h.tenant_id=@tenant AND h.review_id=@id AND h.tests_execution_id=@tests AND h.generation_id=@generation AND h.delivery_run_id=@run AND h.review_package_sha256_digest=@package AND h.evidence_reference=@evidence AND t.candidate_sha256_digest=@candidate AND t.result_sha256_digest=@tests_result";try{await using var cn=await data.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand(sql,cn){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)tenant),("id",NpgsqlDbType.Uuid,id),("tests",NpgsqlDbType.Uuid,tests),("generation",NpgsqlDbType.Uuid,generation),("run",NpgsqlDbType.Uuid,run),("package",NpgsqlDbType.Text,package),("evidence",NpgsqlDbType.Text,evidence),("candidate",NpgsqlDbType.Text,candidate),("tests_result",NpgsqlDbType.Text,testsResult)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var record=JsonSerializer.Deserialize<HumanReviewAtomicRecord>(r.GetString(0))??throw new InvalidOperationException();var test=JsonSerializer.Deserialize<TestsEvidenceRecord>(r.GetString(6))??throw new InvalidOperationException();if(!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),TestsDb.Digest(record))||record.Decision!=HumanReviewDecision.Approve||test.Purpose!=purpose)throw new InvalidOperationException("Human Review evidence binding invalid.");var refs=record.EvidenceReferences.Concat(r.GetFieldValue<string[]>(3)).Append(r.GetString(2)).Distinct(StringComparer.Ordinal).ToImmutableArray();return new(id,tests,record.SandboxExecutionId,record.SecurityValidationId,generation,run,tenant,record.ReviewerSubjectId,GovernedIntentPolicyOutcome.Permit,true,true,false,false,record.Decision,record.Rationale,candidate,test.SecurityReportSha256Digest,test.SandboxResultSha256Digest,testsResult,package,r.GetInt64(5),r.GetString(2),refs,"Separately approved Git boundary",new(r.GetDateTime(4).ToUniversalTime()));}catch(NpgsqlException){throw new GitDependencyUnavailableException("Human Review evidence unavailable.");}}
}

public sealed class PostgreSqlGitTestsReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IGitTestsReceiptReader
{
 public async Task<GovernedTestsExecutionReceipt?> LoadAsync(Guid id,string tenant,string purpose,Guid generation,Guid run,string candidate,string result,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new GitDependencyUnavailableException("Tests evidence not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference,evidence_references,recorded_at FROM software_factory.tests_evidence WHERE tenant_id=@tenant AND execution_id=@id AND generation_id=@generation AND delivery_run_id=@run AND candidate_sha256_digest=@candidate AND result_sha256_digest=@result";try{await using var cn=await data.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand(sql,cn){CommandTimeout=o.CommandTimeoutSeconds};foreach(var item in new[]{("tenant",NpgsqlDbType.Text,(object)tenant),("id",NpgsqlDbType.Uuid,id),("generation",NpgsqlDbType.Uuid,generation),("run",NpgsqlDbType.Uuid,run),("candidate",NpgsqlDbType.Text,candidate),("result",NpgsqlDbType.Text,result)})TestsDb.Add(cmd,item.Item1,item.Item2,item.Item3);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var record=JsonSerializer.Deserialize<TestsEvidenceRecord>(r.GetString(0))??throw new InvalidOperationException();if(record.Purpose!=purpose||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),TestsDb.Digest(record))||record.Result.TimedOut||record.Result.IsolationViolationDetected)throw new InvalidOperationException("Tests evidence binding invalid.");var refs=record.EvidenceReferences.Concat(r.GetFieldValue<string[]>(3)).Append(r.GetString(2)).Distinct(StringComparer.Ordinal).ToImmutableArray();return new(id,record.SandboxExecutionId,record.SecurityValidationId,generation,run,tenant,GovernedIntentPolicyOutcome.Permit,true,false,false,candidate,record.SecurityReportSha256Digest,record.SandboxResultSha256Digest,record.TestManifestSha256Digest,record.TestImage,record.Result.TestResults,result,r.GetString(2),refs,"Separately approved Human Review",new(r.GetDateTime(4).ToUniversalTime()));}catch(NpgsqlException){throw new GitDependencyUnavailableException("Tests evidence unavailable.");}}
}

public sealed class PostgreSqlGitCandidateReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IGitCandidateReader
{
 public async Task<AuthorizedCodeGenerationCandidateSnapshot?> LoadAsync(Guid id,string tenant,string purpose,Guid run,string candidate,CancellationToken ct)=>await new PostgreSqlHumanReviewCandidateReader(data,cfg).LoadAsync(id,tenant,purpose,run,candidate,ct);
}

public sealed class PostgreSqlGitRunReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IGitDeliveryRunReader
{
 public async Task<SoftwareDeliveryRun?> LoadAsync(Guid id,string tenant,string purpose,Guid review,Guid tests,Guid generation,string candidate,string package,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new GitDependencyUnavailableException("Git run not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference FROM software_factory.git_delivery_run_snapshots WHERE tenant_id=@tenant AND run_id=@id AND purpose=@purpose AND review_id=@review AND tests_execution_id=@tests AND generation_id=@generation AND candidate_sha256_digest=@candidate AND review_package_sha256_digest=@package";try{await using var cn=await data.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand(sql,cn){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)tenant),("id",NpgsqlDbType.Uuid,id),("purpose",NpgsqlDbType.Text,purpose),("review",NpgsqlDbType.Uuid,review),("tests",NpgsqlDbType.Uuid,tests),("generation",NpgsqlDbType.Uuid,generation),("candidate",NpgsqlDbType.Text,candidate),("package",NpgsqlDbType.Text,package)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var run=JsonSerializer.Deserialize<SoftwareDeliveryRun>(r.GetString(0))??throw new InvalidOperationException();run.Validate();var digest=TestsDb.Digest(run);if(run.CurrentStage!=DeliveryStage.HumanReview||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),digest)||r.GetString(2)!=$"evidence://delivery-runs/{id:D}/sha256/{digest}")throw new InvalidOperationException("Git run binding invalid.");return run;}catch(NpgsqlException){throw new GitDependencyUnavailableException("Git run unavailable.");}}
}

public sealed class PostgreSqlGitEvidenceRecorder(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IGitEvidenceRecorder
{
 private const string SelectSql="SELECT delivery_run_id,commit_id,change_set_sha256_digest,record_sha256_digest,evidence_reference,recorded_at FROM software_factory.git_evidence WHERE tenant_id=@tenant AND operation_id=@id FOR UPDATE";private const string InsertSql="INSERT INTO software_factory.git_evidence(tenant_id,operation_id,review_id,tests_execution_id,generation_id,delivery_run_id,commit_id,change_set_sha256_digest,record_sha256_digest,record_json,evidence_reference,evidence_references,recorded_at) VALUES(@tenant,@id,@review,@tests,@generation,@run,@commit,@changes,@digest,@json,@evidence,@refs,@at) ON CONFLICT DO NOTHING";
 public async Task<GitEvidenceReceipt> RecordAsync(GitEvidenceRecord record,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new GitDependencyUnavailableException("Git evidence not configured.");var digest=TestsDb.Digest(record);var evidence=$"evidence://git/{record.OperationId:D}/sha256/{digest}";try{await using var cn=await data.OpenConnectionAsync(ct);await using var tx=await cn.BeginTransactionAsync(IsolationLevel.Serializable,ct);var existing=await Load(cn,tx,record.TenantId,record.OperationId,o.CommandTimeoutSeconds,ct);if(existing is not null){Validate(record,digest,existing);await tx.CommitAsync(ct);return existing.Receipt;}await using var cmd=new NpgsqlCommand(InsertSql,cn,tx){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)record.TenantId),("id",NpgsqlDbType.Uuid,record.OperationId),("review",NpgsqlDbType.Uuid,record.ReviewId),("tests",NpgsqlDbType.Uuid,record.TestsExecutionId),("generation",NpgsqlDbType.Uuid,record.GenerationId),("run",NpgsqlDbType.Uuid,record.DeliveryRunId),("commit",NpgsqlDbType.Text,record.Commit.CommitId),("changes",NpgsqlDbType.Text,record.ChangeSet.ChangeSetSha256Digest),("digest",NpgsqlDbType.Text,digest),("json",NpgsqlDbType.Jsonb,JsonSerializer.Serialize(record)),("evidence",NpgsqlDbType.Text,evidence),("refs",NpgsqlDbType.Array|NpgsqlDbType.Text,record.EvidenceReferences.ToArray()),("at",NpgsqlDbType.TimestampTz,record.AuthorizedAt)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);if(await cmd.ExecuteNonQueryAsync(ct)==0){existing=await Load(cn,tx,record.TenantId,record.OperationId,o.CommandTimeoutSeconds,ct)??throw new InvalidOperationException("Git evidence identity conflict.");Validate(record,digest,existing);await tx.CommitAsync(ct);return existing.Receipt;}await tx.CommitAsync(ct);return new(record.OperationId,record.DeliveryRunId,record.TenantId,record.Commit.CommitId,record.ChangeSet.ChangeSetSha256Digest,evidence,record.AuthorizedAt);}catch(NpgsqlException){throw new GitDependencyUnavailableException("Git evidence unavailable.");}}
 private static async Task<Stored?> Load(NpgsqlConnection cn,NpgsqlTransaction tx,string tenant,Guid id,int timeout,CancellationToken ct){await using var cmd=new NpgsqlCommand(SelectSql,cn,tx){CommandTimeout=timeout};TestsDb.Add(cmd,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(cmd,"id",NpgsqlDbType.Uuid,id);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;return new(new(id,r.GetGuid(0),tenant,r.GetString(1),r.GetString(2),r.GetString(4),new(r.GetDateTime(5).ToUniversalTime())),r.GetString(3));}
 private static void Validate(GitEvidenceRecord record,string digest,Stored s){if(s.Receipt.DeliveryRunId!=record.DeliveryRunId||!StringComparer.OrdinalIgnoreCase.Equals(s.Receipt.CommitId,record.Commit.CommitId)||!StringComparer.OrdinalIgnoreCase.Equals(s.Receipt.ChangeSetSha256Digest,record.ChangeSet.ChangeSetSha256Digest)||!StringComparer.OrdinalIgnoreCase.Equals(s.RecordDigest,digest))throw new InvalidOperationException("Stored Git evidence mismatch.");}private sealed record Stored(GitEvidenceReceipt Receipt,string RecordDigest);
}
