using System.Collections.Immutable;
using System.Data;
using System.Text.Json;
using Microsoft.Extensions.Options;
using Npgsql;
using NpgsqlTypes;
using Platform.Domain.Security;
using Platform.Evidence.Chain;
using Platform.SoftwareFactory.Delivery;
using Platform.SoftwareFactory.InternalService;

namespace Platform.SoftwareFactory.Persistence;

public sealed class PostgreSqlAuthorizedEnterpriseModelContextualizationReceiptReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> configured):IAuthorizedEnterpriseModelContextualizationReceiptReader
{
 public async Task<GovernedEnterpriseModelContextualizationReceipt?> LoadAsync(Guid id,string tenant,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EvidenceCompletionDependencyUnavailableException("Enterprise Model evidence is not configured.");const string sql="SELECT delivery_run_id,record_json,record_sha256_digest,evidence_reference,evidence_references,recorded_at FROM software_factory.enterprise_model_context_evidence WHERE tenant_id=@tenant AND contextualization_id=@id";try{await using var c=await data.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand(sql,c){CommandTimeout=o.CommandTimeoutSeconds};TestsDb.Add(q,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(q,"id",NpgsqlDbType.Uuid,id);await using var r=await q.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var x=JsonSerializer.Deserialize<EnterpriseModelContextEvidenceRecord>(r.GetString(1))??throw new InvalidOperationException("Stored Enterprise Model evidence is empty.");var d=TestsDb.Digest(x);var e=r.GetString(3);if(x.ContextualizationId!=id||x.TenantId!=tenant||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(2),d)||e!=$"evidence://enterprise-model/{id:D}/sha256/{d}")throw new InvalidOperationException("Stored Enterprise Model evidence binding is invalid.");var refs=x.EvidenceReferences.Concat(r.GetFieldValue<string[]>(4)).Append(e).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToImmutableArray();return new(id,x.RegistrationId,x.DeliveryRunId,tenant,GovernedIntentPolicyOutcome.Permit,true,true,false,false,false,false,x.EnterpriseObject.Id,"sha256:"+new string('0',64),e,refs,"Separately approved Evidence completion",new(r.GetDateTime(5).ToUniversalTime()));}catch(NpgsqlException){throw new EvidenceCompletionDependencyUnavailableException("Enterprise Model evidence is unavailable.");}}
}

public sealed class PostgreSqlEvidenceCompletionRunReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> configured):IEvidenceCompletionDeliveryRunReader
{
 public async Task<SoftwareDeliveryRun?> LoadAsync(Guid id,string tenant,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EvidenceCompletionDependencyUnavailableException("Evidence completion run is not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference FROM software_factory.evidence_completion_delivery_run_snapshots WHERE tenant_id=@tenant AND run_id=@id";try{await using var c=await data.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand(sql,c){CommandTimeout=o.CommandTimeoutSeconds};TestsDb.Add(q,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(q,"id",NpgsqlDbType.Uuid,id);await using var r=await q.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var run=JsonSerializer.Deserialize<SoftwareDeliveryRun>(r.GetString(0))??throw new InvalidOperationException("Stored Evidence completion run is empty.");run.Validate();var d=TestsDb.Digest(run);if(run.CurrentStage!=DeliveryStage.EnterpriseModel||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),d)||r.GetString(2)!=$"evidence://delivery-runs/{id:D}/sha256/{d}")throw new InvalidOperationException("Stored Evidence completion run binding is invalid.");return run;}catch(NpgsqlException){throw new EvidenceCompletionDependencyUnavailableException("Evidence completion run is unavailable.");}}
}

public sealed class PostgreSqlEvidenceChainStore(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> configured):IEvidenceChainStore
{
 public Task<EvidenceEntry?> LoadHeadAsync(Guid chain,string tenant,CancellationToken ct)=>LoadOne(chain,tenant,true,ct);
 public async Task<EvidenceEntry> AppendAtomicallyAsync(EvidenceEntry entry,long expectedSequence,string expectedHash,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EvidenceCompletionDependencyUnavailableException("Evidence chain store is not configured.");try{await using var c=await data.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);var head=await LoadOne(c,t,entry.ChainId,entry.TenantId,o.CommandTimeoutSeconds,ct);if((head?.Sequence??-1)!=expectedSequence||!StringComparer.OrdinalIgnoreCase.Equals(head?.EntrySha256Digest??EvidenceValidation.GenesisSha256Digest,expectedHash))throw new InvalidOperationException("Evidence chain head changed before append.");const string sql="INSERT INTO evidence.chain_entries(tenant_id,chain_id,sequence,stage,classification,entry_sha256_digest,record_json,occurred_at) VALUES(@tenant,@chain,@sequence,@stage,@classification,@digest,@json,@at) ON CONFLICT DO NOTHING";await using var q=new NpgsqlCommand(sql,c,t){CommandTimeout=o.CommandTimeoutSeconds};foreach(var v in new[]{("tenant",NpgsqlDbType.Text,(object)entry.TenantId),("chain",NpgsqlDbType.Uuid,entry.ChainId),("sequence",NpgsqlDbType.Bigint,entry.Sequence),("stage",NpgsqlDbType.Text,entry.Stage.ToString()),("classification",NpgsqlDbType.Text,entry.Classification),("digest",NpgsqlDbType.Text,entry.EntrySha256Digest),("json",NpgsqlDbType.Jsonb,JsonSerializer.Serialize(entry)),("at",NpgsqlDbType.TimestampTz,entry.OccurredAt)})TestsDb.Add(q,v.Item1,v.Item2,v.Item3);if(await q.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Evidence append conflicted with an existing entry.");await t.CommitAsync(ct);return entry;}catch(NpgsqlException){throw new EvidenceCompletionDependencyUnavailableException("Evidence chain store is unavailable.");}}
 public async Task<ImmutableArray<EvidenceEntry>> LoadOrderedAsync(Guid chain,string tenant,string maximum,string authorization,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EvidenceCompletionDependencyUnavailableException("Evidence chain store is not configured.");if(!Enum.TryParse<DataClassification>(maximum,true,out var max))throw new UnauthorizedAccessException("Evidence classification scope is invalid.");const string sql="SELECT record_json FROM evidence.chain_entries WHERE tenant_id=@tenant AND chain_id=@chain ORDER BY sequence";try{await using var c=await data.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand(sql,c){CommandTimeout=o.CommandTimeoutSeconds};TestsDb.Add(q,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(q,"chain",NpgsqlDbType.Uuid,chain);await using var r=await q.ExecuteReaderAsync(ct);var b=ImmutableArray.CreateBuilder<EvidenceEntry>();while(await r.ReadAsync(ct)){var x=JsonSerializer.Deserialize<EvidenceEntry>(r.GetString(0))??throw new InvalidOperationException("Stored Evidence entry is empty.");if(!Enum.TryParse<DataClassification>(x.Classification,true,out var actual)||actual>max)throw new UnauthorizedAccessException("Evidence entry exceeds authorized classification.");b.Add(x);}return b.ToImmutable();}catch(NpgsqlException){throw new EvidenceCompletionDependencyUnavailableException("Evidence chain store is unavailable.");}}
 private async Task<EvidenceEntry?> LoadOne(Guid chain,string tenant,bool head,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EvidenceCompletionDependencyUnavailableException("Evidence chain store is not configured.");try{await using var c=await data.OpenConnectionAsync(ct);return await LoadOne(c,null,chain,tenant,o.CommandTimeoutSeconds,ct);}catch(NpgsqlException){throw new EvidenceCompletionDependencyUnavailableException("Evidence chain store is unavailable.");}}
 private static async Task<EvidenceEntry?> LoadOne(NpgsqlConnection c,NpgsqlTransaction? t,Guid chain,string tenant,int timeout,CancellationToken ct){const string sql="SELECT record_json FROM evidence.chain_entries WHERE tenant_id=@tenant AND chain_id=@chain ORDER BY sequence DESC LIMIT 1 FOR UPDATE";await using var q=new NpgsqlCommand(sql,c,t){CommandTimeout=timeout};TestsDb.Add(q,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(q,"chain",NpgsqlDbType.Uuid,chain);var raw=await q.ExecuteScalarAsync(ct);return raw is null?null:JsonSerializer.Deserialize<EvidenceEntry>((string)raw)??throw new InvalidOperationException("Stored Evidence head is empty.");}
}
