using System.Collections.Immutable;
using System.Data;
using System.Text.Json;
using Microsoft.Extensions.Options;
using Npgsql;
using NpgsqlTypes;
using Platform.EnterpriseModel.Model;
using Platform.SoftwareFactory.Delivery;
using Platform.SoftwareFactory.InternalService;

namespace Platform.SoftwareFactory.Persistence;

public sealed class PostgreSqlAuthorizedAutomaticRegistrationReceiptReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> configured):IAuthorizedAutomaticRegistrationReceiptReader
{
 public async Task<GovernedAutomaticRegistrationReceipt?> LoadAsync(Guid id,string tenant,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EnterpriseModelDependencyUnavailableException("Automatic Registration evidence is not configured.");const string sql="SELECT delivery_run_id,record_json,record_sha256_digest,evidence_reference,evidence_references,recorded_at FROM software_factory.automatic_registration_evidence WHERE tenant_id=@tenant AND registration_id=@id";try{await using var c=await data.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand(sql,c){CommandTimeout=o.CommandTimeoutSeconds};TestsDb.Add(q,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(q,"id",NpgsqlDbType.Uuid,id);await using var r=await q.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var x=JsonSerializer.Deserialize<AutomaticRegistrationEvidenceRecord>(r.GetString(1))??throw new InvalidOperationException("Stored Automatic Registration evidence is empty.");var digest=TestsDb.Digest(x);var evidence=r.GetString(3);if(x.RegistrationId!=id||x.TenantId!=tenant||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(2),digest)||evidence!=$"evidence://automatic-registration/{id:D}/sha256/{digest}")throw new InvalidOperationException("Stored Automatic Registration evidence binding is invalid.");var refs=x.EvidenceReferences.Concat(r.GetFieldValue<string[]>(4)).Append(evidence).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToImmutableArray();return new(id,x.ActivationId,x.DeliveryRunId,tenant,GovernedIntentPolicyOutcome.Permit,true,true,true,false,false,x.Manifest.ServiceIdentity,x.Manifest.ServiceVersion,x.Manifest.RuntimeIdentity,x.Manifest.ArtifactDigest,x.Commit.RequestFingerprint,x.Commit.Disposition,x.Commit.EnterpriseObject.Id,evidence,refs,"Separately approved Enterprise Model contextualization",new(r.GetDateTime(5).ToUniversalTime()));}catch(NpgsqlException){throw new EnterpriseModelDependencyUnavailableException("Automatic Registration evidence is unavailable.");}}
}

public sealed class PostgreSqlEnterpriseModelRunReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> configured):IEnterpriseModelDeliveryRunReader
{
 public async Task<SoftwareDeliveryRun?> LoadAsync(Guid id,string tenant,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EnterpriseModelDependencyUnavailableException("Enterprise Model run evidence is not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference FROM software_factory.enterprise_model_delivery_run_snapshots WHERE tenant_id=@tenant AND run_id=@id";try{await using var c=await data.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand(sql,c){CommandTimeout=o.CommandTimeoutSeconds};TestsDb.Add(q,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(q,"id",NpgsqlDbType.Uuid,id);await using var r=await q.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var run=JsonSerializer.Deserialize<SoftwareDeliveryRun>(r.GetString(0))??throw new InvalidOperationException("Stored Enterprise Model run is empty.");run.Validate();var d=TestsDb.Digest(run);if(run.CurrentStage!=DeliveryStage.AutomaticRegistration||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),d)||r.GetString(2)!=$"evidence://delivery-runs/{id:D}/sha256/{d}")throw new InvalidOperationException("Stored Enterprise Model run binding is invalid.");return run;}catch(NpgsqlException){throw new EnterpriseModelDependencyUnavailableException("Enterprise Model run evidence is unavailable.");}}
}

public sealed class PostgreSqlAuthorizedRegisteredEnterpriseObjectReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> configured):IAuthorizedRegisteredEnterpriseObjectReader
{
 public async Task<EnterpriseObject?> LoadAsync(EnterpriseObjectId id,string tenant,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EnterpriseModelDependencyUnavailableException("Registered Enterprise Objects are not configured.");const string sql="SELECT enterprise_object_json FROM software_factory.automatic_registrations WHERE tenant_id=@tenant AND enterprise_object_id=@id";try{await using var c=await data.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand(sql,c){CommandTimeout=o.CommandTimeoutSeconds};TestsDb.Add(q,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(q,"id",NpgsqlDbType.Uuid,id.Value);var raw=await q.ExecuteScalarAsync(ct);if(raw is null)return null;var value=JsonSerializer.Deserialize<EnterpriseObject>((string)raw)??throw new InvalidOperationException("Stored registered Enterprise Object is empty.");value.Validate();if(value.Id!=id||value.TenantId!=tenant)throw new InvalidOperationException("Stored Enterprise Object binding is invalid.");return value;}catch(NpgsqlException){throw new EnterpriseModelDependencyUnavailableException("Registered Enterprise Objects are unavailable.");}}
}

public sealed class PostgreSqlEnterpriseModelContextEvidenceRecorder(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> configured):IEnterpriseModelContextEvidenceRecorder
{
 private const string SelectSql="SELECT delivery_run_id,enterprise_object_id,record_sha256_digest,evidence_reference,recorded_at FROM software_factory.enterprise_model_context_evidence WHERE tenant_id=@tenant AND contextualization_id=@id FOR UPDATE";
 public async Task<EnterpriseModelContextEvidenceReceipt> RecordAsync(EnterpriseModelContextEvidenceRecord x,CancellationToken ct){var o=configured.Value;if(!o.IsOperationallyConfigured)throw new EnterpriseModelDependencyUnavailableException("Enterprise Model evidence is not configured.");var d=TestsDb.Digest(x);var e=$"evidence://enterprise-model/{x.ContextualizationId:D}/sha256/{d}";try{await using var c=await data.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);var old=await Load(c,t,x.TenantId,x.ContextualizationId,o.CommandTimeoutSeconds,ct);if(old is not null){Validate(x,d,old);await t.CommitAsync(ct);return old.Receipt;}const string sql="INSERT INTO software_factory.enterprise_model_context_evidence(tenant_id,contextualization_id,registration_id,delivery_run_id,enterprise_object_id,record_sha256_digest,record_json,evidence_reference,evidence_references,recorded_at) VALUES(@tenant,@id,@registration,@run,@object,@digest,@json,@evidence,@refs,@at) ON CONFLICT DO NOTHING";await using var q=new NpgsqlCommand(sql,c,t){CommandTimeout=o.CommandTimeoutSeconds};foreach(var v in new[]{("tenant",NpgsqlDbType.Text,(object)x.TenantId),("id",NpgsqlDbType.Uuid,x.ContextualizationId),("registration",NpgsqlDbType.Uuid,x.RegistrationId),("run",NpgsqlDbType.Uuid,x.DeliveryRunId),("object",NpgsqlDbType.Uuid,x.EnterpriseObject.Id.Value),("digest",NpgsqlDbType.Text,d),("json",NpgsqlDbType.Jsonb,JsonSerializer.Serialize(x)),("evidence",NpgsqlDbType.Text,e),("refs",NpgsqlDbType.Array|NpgsqlDbType.Text,x.EvidenceReferences.ToArray()),("at",NpgsqlDbType.TimestampTz,x.AuthorizedAt)})TestsDb.Add(q,v.Item1,v.Item2,v.Item3);if(await q.ExecuteNonQueryAsync(ct)==0){old=await Load(c,t,x.TenantId,x.ContextualizationId,o.CommandTimeoutSeconds,ct)??throw new InvalidOperationException("Enterprise Model evidence identity conflict.");Validate(x,d,old);await t.CommitAsync(ct);return old.Receipt;}await t.CommitAsync(ct);return new(x.ContextualizationId,x.DeliveryRunId,x.EnterpriseObject.Id,x.TenantId,e,x.AuthorizedAt);}catch(NpgsqlException){throw new EnterpriseModelDependencyUnavailableException("Enterprise Model evidence is unavailable.");}}
 private static async Task<Stored?> Load(NpgsqlConnection c,NpgsqlTransaction t,string tenant,Guid id,int timeout,CancellationToken ct){await using var q=new NpgsqlCommand(SelectSql,c,t){CommandTimeout=timeout};TestsDb.Add(q,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(q,"id",NpgsqlDbType.Uuid,id);await using var r=await q.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;return new(new(id,r.GetGuid(0),new EnterpriseObjectId(r.GetGuid(1)),tenant,r.GetString(3),new(r.GetDateTime(4).ToUniversalTime())),r.GetString(2));}
 private static void Validate(EnterpriseModelContextEvidenceRecord x,string d,Stored old){if(old.Receipt.DeliveryRunId!=x.DeliveryRunId||old.Receipt.EnterpriseObjectId!=x.EnterpriseObject.Id||!StringComparer.OrdinalIgnoreCase.Equals(old.Digest,d))throw new InvalidOperationException("Stored Enterprise Model evidence does not match the result.");}
 private sealed record Stored(EnterpriseModelContextEvidenceReceipt Receipt,string Digest);
}
