using System.Collections.Immutable;
using System.Data;
using System.Text.Json;
using Microsoft.Extensions.Options;
using Npgsql;
using NpgsqlTypes;
using Platform.SoftwareFactory.Delivery;
using Platform.SoftwareFactory.InternalService;

namespace Platform.SoftwareFactory.Persistence;

public sealed class PostgreSqlHumanReviewTestsReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IHumanReviewTestsReceiptReader
{
    public async Task<GovernedTestsExecutionReceipt?> LoadAsync(Guid id,string tenant,string purpose,Guid sandbox,Guid security,Guid generation,Guid run,string candidate,string securityDigest,string sandboxDigest,string result,string evidence,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new HumanReviewDependencyUnavailableException("Tests evidence not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference,evidence_references,recorded_at FROM software_factory.tests_evidence WHERE tenant_id=@tenant AND execution_id=@id AND sandbox_execution_id=@sandbox AND security_validation_id=@security AND generation_id=@generation AND delivery_run_id=@run AND candidate_sha256_digest=@candidate AND security_report_sha256_digest=@security_digest AND sandbox_result_sha256_digest=@sandbox_digest AND result_sha256_digest=@result AND evidence_reference=@evidence";try{await using var cn=await data.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand(sql,cn){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)tenant),("id",NpgsqlDbType.Uuid,id),("sandbox",NpgsqlDbType.Uuid,sandbox),("security",NpgsqlDbType.Uuid,security),("generation",NpgsqlDbType.Uuid,generation),("run",NpgsqlDbType.Uuid,run),("candidate",NpgsqlDbType.Text,candidate),("security_digest",NpgsqlDbType.Text,securityDigest),("sandbox_digest",NpgsqlDbType.Text,sandboxDigest),("result",NpgsqlDbType.Text,result),("evidence",NpgsqlDbType.Text,evidence)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var record=JsonSerializer.Deserialize<TestsEvidenceRecord>(r.GetString(0))??throw new InvalidOperationException();var digest=TestsDb.Digest(record);if(record.Purpose!=purpose||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),digest)||r.GetString(2)!=$"evidence://tests/{id:D}/sha256/{digest}"||record.Result.TimedOut||record.Result.IsolationViolationDetected)throw new InvalidOperationException("Tests evidence binding invalid.");var refs=record.EvidenceReferences.Concat(r.GetFieldValue<string[]>(3)).Append(r.GetString(2)).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToImmutableArray();return new(id,sandbox,security,generation,run,tenant,GovernedIntentPolicyOutcome.Permit,true,false,false,candidate,securityDigest,sandboxDigest,record.TestManifestSha256Digest,record.TestImage,record.Result.TestResults,result,r.GetString(2),refs,"Separately approved Human Review",new(r.GetDateTime(4).ToUniversalTime()));}catch(NpgsqlException){throw new HumanReviewDependencyUnavailableException("Tests evidence unavailable.");}}
}

public sealed class PostgreSqlHumanReviewSandboxReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IHumanReviewSandboxReceiptReader
{
    public async Task<GovernedSandboxExecutionReceipt?> LoadAsync(Guid id,string tenant,string purpose,Guid security,Guid generation,Guid run,string candidate,string report,string result,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new HumanReviewDependencyUnavailableException("Sandbox evidence not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference,evidence_references,recorded_at FROM software_factory.sandbox_evidence WHERE tenant_id=@tenant AND execution_id=@id AND security_validation_id=@security AND generation_id=@generation AND delivery_run_id=@run AND candidate_sha256_digest=@candidate AND security_report_sha256_digest=@report AND result_sha256_digest=@result";try{await using var cn=await data.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand(sql,cn){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)tenant),("id",NpgsqlDbType.Uuid,id),("security",NpgsqlDbType.Uuid,security),("generation",NpgsqlDbType.Uuid,generation),("run",NpgsqlDbType.Uuid,run),("candidate",NpgsqlDbType.Text,candidate),("report",NpgsqlDbType.Text,report),("result",NpgsqlDbType.Text,result)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var record=JsonSerializer.Deserialize<SandboxEvidenceRecord>(r.GetString(0))??throw new InvalidOperationException();var digest=TestsDb.Digest(record);if(record.Purpose!=purpose||!record.Result.IsAccepted||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),digest))throw new InvalidOperationException("Sandbox evidence binding invalid.");var refs=record.EvidenceReferences.Concat(r.GetFieldValue<string[]>(3)).Append(r.GetString(2)).Distinct(StringComparer.Ordinal).ToImmutableArray();return new(id,security,generation,run,tenant,GovernedIntentPolicyOutcome.Permit,true,false,false,candidate,report,record.SandboxImage,record.Result.ExitCode,record.Result.TimedOut,record.Result.IsolationViolationDetected,record.Result.ProducedArtifactReferences,result,r.GetString(2),refs,"Separately approved Tests",new(r.GetDateTime(4).ToUniversalTime()));}catch(NpgsqlException){throw new HumanReviewDependencyUnavailableException("Sandbox evidence unavailable.");}}
}

public sealed class PostgreSqlHumanReviewSecurityReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IHumanReviewSecurityReceiptReader
{
    public async Task<GovernedSecurityValidationReceipt?> LoadAsync(Guid id,string tenant,string purpose,Guid generation,Guid run,string candidate,string report,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new HumanReviewDependencyUnavailableException("Security evidence not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference,evidence_references,recorded_at FROM software_factory.security_validation_evidence WHERE tenant_id=@tenant AND validation_id=@id AND generation_id=@generation AND delivery_run_id=@run AND candidate_sha256_digest=@candidate AND security_report_sha256_digest=@report";try{await using var cn=await data.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand(sql,cn){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)tenant),("id",NpgsqlDbType.Uuid,id),("generation",NpgsqlDbType.Uuid,generation),("run",NpgsqlDbType.Uuid,run),("candidate",NpgsqlDbType.Text,candidate),("report",NpgsqlDbType.Text,report)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var record=JsonSerializer.Deserialize<SecurityValidationEvidenceRecord>(r.GetString(0))??throw new InvalidOperationException();if(record.Purpose!=purpose||!record.Report.IsAccepted||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),TestsDb.Digest(record)))throw new InvalidOperationException("Security evidence binding invalid.");var refs=record.EvidenceReferences.Concat(r.GetFieldValue<string[]>(3)).Append(r.GetString(2)).Distinct(StringComparer.Ordinal).ToImmutableArray();return new(id,record.StaticValidationId,generation,run,tenant,GovernedIntentPolicyOutcome.Permit,Validation.ValidationGate.Security,true,false,false,candidate,record.StaticReportSha256Digest,report,record.Report.ControlReports,r.GetString(2),refs,"Separately approved Sandbox",new(r.GetDateTime(4).ToUniversalTime()));}catch(NpgsqlException){throw new HumanReviewDependencyUnavailableException("Security evidence unavailable.");}}
}

public sealed class PostgreSqlHumanReviewCandidateReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IHumanReviewCandidateReader
{
    public async Task<AuthorizedCodeGenerationCandidateSnapshot?> LoadAsync(Guid id,string tenant,string purpose,Guid run,string candidate,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new HumanReviewDependencyUnavailableException("Candidate evidence not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference,evidence_references,recorded_at FROM software_factory.code_generation_evidence WHERE tenant_id=@tenant AND generation_id=@id AND delivery_run_id=@run AND candidate_sha256_digest=@candidate";try{await using var cn=await data.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand(sql,cn){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)tenant),("id",NpgsqlDbType.Uuid,id),("run",NpgsqlDbType.Uuid,run),("candidate",NpgsqlDbType.Text,candidate)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var record=JsonSerializer.Deserialize<CodeGenerationEvidenceRecord>(r.GetString(0))??throw new InvalidOperationException();record.Candidate.Validate();if(record.Purpose!=purpose||!record.Evaluation.IsAccepted||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),TestsDb.Digest(record)))throw new InvalidOperationException("Candidate evidence binding invalid.");var refs=record.EvidenceReferences.Concat(r.GetFieldValue<string[]>(3)).Append(r.GetString(2)).Distinct(StringComparer.Ordinal).ToImmutableArray();return new(new(id,record.PlanningId,record.PackageSelectionId,run,tenant,GovernedIntentPolicyOutcome.Permit,true,false,false,false,candidate,record.Candidate.Content,record.Candidate.GeneratedFilePaths,record.Evaluation.Findings,r.GetString(2),refs,"Separately approved Static Validation",new(r.GetDateTime(4).ToUniversalTime())),record.Candidate);}catch(NpgsqlException){throw new HumanReviewDependencyUnavailableException("Candidate evidence unavailable.");}}
}

public sealed class PostgreSqlHumanReviewRunReader(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IHumanReviewDeliveryRunReader
{
    public async Task<SoftwareDeliveryRun?> LoadAsync(Guid id,string tenant,string purpose,Guid tests,Guid sandbox,Guid generation,string candidate,string result,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new HumanReviewDependencyUnavailableException("Human Review run not configured.");const string sql="SELECT record_json,record_sha256_digest,evidence_reference FROM software_factory.human_review_delivery_run_snapshots WHERE tenant_id=@tenant AND run_id=@id AND purpose=@purpose AND tests_execution_id=@tests AND sandbox_execution_id=@sandbox AND generation_id=@generation AND candidate_sha256_digest=@candidate AND tests_result_sha256_digest=@result";try{await using var cn=await data.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand(sql,cn){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)tenant),("id",NpgsqlDbType.Uuid,id),("purpose",NpgsqlDbType.Text,purpose),("tests",NpgsqlDbType.Uuid,tests),("sandbox",NpgsqlDbType.Uuid,sandbox),("generation",NpgsqlDbType.Uuid,generation),("candidate",NpgsqlDbType.Text,candidate),("result",NpgsqlDbType.Text,result)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var run=JsonSerializer.Deserialize<SoftwareDeliveryRun>(r.GetString(0))??throw new InvalidOperationException();run.Validate();var digest=TestsDb.Digest(run);if(run.CurrentStage!=DeliveryStage.Tests||!StringComparer.OrdinalIgnoreCase.Equals(r.GetString(1),digest)||r.GetString(2)!=$"evidence://delivery-runs/{id:D}/sha256/{digest}")throw new InvalidOperationException("Human Review run binding invalid.");return run;}catch(NpgsqlException){throw new HumanReviewDependencyUnavailableException("Human Review run unavailable.");}}
}

public sealed class PostgreSqlAtomicHumanReviewRepository(NpgsqlDataSource data,IOptions<PostgreSqlIntentRegistrationOptions> cfg):IAtomicHumanReviewRepository
{
    private const string SelectSql="SELECT delivery_run_id,reviewer_subject_id,decision,rationale,human_attestation_reference,review_package_sha256_digest,version,evidence_reference,evidence_references,recorded_at,record_sha256_digest FROM software_factory.human_review_evidence WHERE tenant_id=@tenant AND review_id=@id FOR UPDATE";
    private const string InsertSql="INSERT INTO software_factory.human_review_evidence(tenant_id,review_id,tests_execution_id,sandbox_execution_id,security_validation_id,generation_id,delivery_run_id,reviewer_subject_id,decision,rationale,human_attestation_reference,review_package_sha256_digest,policy_decision_request_id,policy_bundle_sha256_digest,version,record_sha256_digest,record_json,evidence_reference,evidence_references,recorded_at) VALUES(@tenant,@id,@tests,@sandbox,@security,@generation,@run,@reviewer,@decision,@rationale,@attestation,@package,@policy,@bundle,@version,@digest,@json,@evidence,@refs,@at) ON CONFLICT DO NOTHING";
    public async Task<HumanReviewAtomicReceipt> RecordDecisionAndEvidenceAsync(HumanReviewAtomicRecord record,long expected,CancellationToken ct){var o=cfg.Value;if(!o.IsOperationallyConfigured)throw new HumanReviewDependencyUnavailableException("Human Review repository not configured.");var digest=TestsDb.Digest(record);var evidence=$"evidence://human-review/{record.ReviewId:D}/sha256/{digest}";try{await using var cn=await data.OpenConnectionAsync(ct);await using var tx=await cn.BeginTransactionAsync(IsolationLevel.Serializable,ct);var existing=await Load(cn,tx,record.TenantId,record.ReviewId,o.CommandTimeoutSeconds,ct);if(existing is not null){Validate(record,expected,digest,existing);await tx.CommitAsync(ct);return existing.Receipt;}if(expected!=-1)throw new InvalidOperationException("Human Review optimistic version conflict.");await using var cmd=new NpgsqlCommand(InsertSql,cn,tx){CommandTimeout=o.CommandTimeoutSeconds};foreach(var x in new[]{("tenant",NpgsqlDbType.Text,(object)record.TenantId),("id",NpgsqlDbType.Uuid,record.ReviewId),("tests",NpgsqlDbType.Uuid,record.TestsExecutionId),("sandbox",NpgsqlDbType.Uuid,record.SandboxExecutionId),("security",NpgsqlDbType.Uuid,record.SecurityValidationId),("generation",NpgsqlDbType.Uuid,record.GenerationId),("run",NpgsqlDbType.Uuid,record.DeliveryRunId),("reviewer",NpgsqlDbType.Text,record.ReviewerSubjectId),("decision",NpgsqlDbType.Text,record.Decision.ToString()),("rationale",NpgsqlDbType.Text,record.Rationale),("attestation",NpgsqlDbType.Text,record.HumanAttestationReference),("package",NpgsqlDbType.Text,record.ReviewPackageSha256Digest),("policy",NpgsqlDbType.Uuid,record.PolicyDecisionRequestId),("bundle",NpgsqlDbType.Text,record.PolicyBundleSha256Digest),("version",NpgsqlDbType.Bigint,expected+1),("digest",NpgsqlDbType.Text,digest),("json",NpgsqlDbType.Jsonb,JsonSerializer.Serialize(record)),("evidence",NpgsqlDbType.Text,evidence),("refs",NpgsqlDbType.Array|NpgsqlDbType.Text,record.EvidenceReferences.ToArray()),("at",NpgsqlDbType.TimestampTz,record.ReviewedAt)})TestsDb.Add(cmd,x.Item1,x.Item2,x.Item3);if(await cmd.ExecuteNonQueryAsync(ct)==0){existing=await Load(cn,tx,record.TenantId,record.ReviewId,o.CommandTimeoutSeconds,ct)??throw new InvalidOperationException("Human Review identity conflict.");Validate(record,expected,digest,existing);await tx.CommitAsync(ct);return existing.Receipt;}await tx.CommitAsync(ct);return new(record.ReviewId,record.DeliveryRunId,record.TenantId,record.ReviewerSubjectId,record.Decision,record.Rationale,record.HumanAttestationReference,record.ReviewPackageSha256Digest,expected+1,evidence,record.EvidenceReferences.Append(evidence).ToImmutableArray(),record.ReviewedAt);}catch(NpgsqlException){throw new HumanReviewDependencyUnavailableException("Human Review repository unavailable.");}}
    private static async Task<Stored?> Load(NpgsqlConnection cn,NpgsqlTransaction tx,string tenant,Guid id,int timeout,CancellationToken ct){await using var cmd=new NpgsqlCommand(SelectSql,cn,tx){CommandTimeout=timeout};TestsDb.Add(cmd,"tenant",NpgsqlDbType.Text,tenant);TestsDb.Add(cmd,"id",NpgsqlDbType.Uuid,id);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;var receipt=new HumanReviewAtomicReceipt(id,r.GetGuid(0),tenant,r.GetString(1),Enum.Parse<HumanReviewDecision>(r.GetString(2)),r.GetString(3),r.GetString(4),r.GetString(5),r.GetInt64(6),r.GetString(7),r.GetFieldValue<string[]>(8).ToImmutableArray(),new(r.GetDateTime(9).ToUniversalTime()));return new(receipt,r.GetString(10));}
    private static void Validate(HumanReviewAtomicRecord record,long expected,string digest,Stored stored){var r=stored.Receipt;if(r.DeliveryRunId!=record.DeliveryRunId||r.ReviewerSubjectId!=record.ReviewerSubjectId||r.Decision!=record.Decision||r.Rationale!=record.Rationale||r.HumanAttestationReference!=record.HumanAttestationReference||!StringComparer.OrdinalIgnoreCase.Equals(r.ReviewPackageSha256Digest,record.ReviewPackageSha256Digest)||r.Version!=expected+1||!StringComparer.OrdinalIgnoreCase.Equals(stored.RecordDigest,digest))throw new InvalidOperationException("Stored Human Review evidence mismatch.");}
    private sealed record Stored(HumanReviewAtomicReceipt Receipt,string RecordDigest);
}
